### ISSUE TITLE
I think it is nice because both losses are close to 0, but it still cannot detect anything in the training dataset.

### ISSUE THREAD

**Issue by Aaron4Fun** [jianing-sun/Food-Detection-by-YOLOv2-with-Transfer-Learning#2]
I think it is nice because both losses are close to 0, but it still cannot detect anything in the training dataset. And the train_loss is higher than val_loss most of the time.

_Originally posted by @Aaron4Fun in https://github.com/jianing-sun/Food-Detection-by-YOLOv2-with-Transfer-Learning/issues/1#issuecomment-462171021_

**Comment by jianing-sun** [comment]
Some question answered in #1. This issue will be closed. Thanks
